# Nombre de tu aplicación
spring.application.name=Hogwarts

# Configuración de base de datos (Spring las buscará en las variables de entorno de AWS)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACIÓN DE SWAGGER (Para que funcione tu URL /documentacion)
springdoc.swagger-ui.path=/documentacion
springdoc.api-docs.path=/v3/api-docs