# Conexión a tu base de datos en AWS (copiado de tu imagen)
spring.datasource.url=jdbc:postgresql://postgres.cdumlx3lpig8.us-east-1.rds.amazonaws.com:5432/postgres

# El usuario suele ser 'postgres' por defecto en AWS, a menos que crearas otro.
spring.datasource.username=postgres

# ¡AQUÍ PON LA CONTRASEÑA QUE USASTE PARA CONECTARTE EN INTELLIJ!
spring.datasource.password=postgres

# Configuración Swagger
springdoc.swagger-ui.path=/documentacion
springdoc.swagger-ui.operationsSorter=method

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect