# Configuración de la aplicación
spring.application.name=Hogwarts

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACIÓN DE SWAGGER (OPENAPI) - ESTO ES LO QUE TE FALTA
springdoc.swagger-ui.path=/documentacion
springdoc.swagger-ui.operationsSorter=method

# Nota: No ponemos spring.datasource.url ni credenciales aquí
# porque AWS las inyecta automáticamente desde el entorno.